### PR TITLE
Implemented dim analysis function

### PR DESCRIPTION
**Pull request by royerloic**
This function guesses whether the dims of an array are spatio-tempora, bacth or channel.

### CODE REVIEW

**Comment by AhmetCanSolak** [comment]
Thank you for the PR @royerloic ! I will test it in detail and get it merged soon.

**Review by AhmetCanSolak — COMMENTED** [review]
It seems the test is currently failing. Since you mentioned you will be updating the branch @royerloic , I wanted to the mention the test too. You are probably fixing/improving some other points too. I am waiting your latest changes to review this PR further.

```
test_dimension_analysis.py::test_dimension_analysis FAILED               [100%]
(0, 2)
()

aydin/analysis/test/test_dimension_analysis.py:4 (test_dimension_analysis)
def test_dimension_analysis():
    
        image = examples_single.maitre_mouse.get_array()
    
        batch_axes, channel_axes = dimension_analysis_on_image(image)
    
        print(batch_axes)
        print(channel_axes)
    
        assert len(channel_axes) == 0
        assert len(batch_axes) == 2
>       assert 0 in batch_axes and 1 in batch_axes
E       assert (0 in (0, 2) and 1 in (0, 2))

test_dimension_analysis.py:16: AssertionError
```

**Comment by royerloic** [comment]
Just pushed some changes, might help...

**Comment by royerloic** [comment]
The code is much slower than before, but most likely more accurate. 
Perhaps it needs a bit more work.

**Review by AhmetCanSolak — CHANGES_REQUESTED** [review]
It feels slower but I think that is okay @royerloic . We can have a button and spinner if needed on the GUI. 

Currently some tests are failing, see below:
```
def test_dimension_analysis_cognet():
    
        image = examples_single.cognet_nanotube_400fps.get_array()
    
        batch_axes, channel_axes = dimension_analysis_on_image(
            image, algorithm='butterworth'
        )
    
        print(batch_axes)
        print(channel_axes)
    
        assert len(channel_axes) == 0
>       assert len(batch_axes) == 2
E       assert 1 == 2


def test_dimension_analysis_huang():
    
        image = examples_single.huang_fixed_pattern_noise.get_array()
    
        batch_axes, channel_axes = dimension_analysis_on_image(
            image, algorithm='butterworth'
        )
    
        print(batch_axes)
        print(channel_axes)
    
        assert len(channel_axes) == 0
        assert len(batch_axes) == 1
>       assert 2 in batch_axes
E       assert 2 in (0,)


def test_dimension_analysis_royer():
    
        image = examples_single.royerlab_hcr.get_array()
    
        batch_axes, channel_axes = dimension_analysis_on_image(
            image, algorithm='butterworth', max_channels_per_axis=6
        )
    
        print(batch_axes)
        print(channel_axes)
    
        assert len(channel_axes) == 0
>       assert len(batch_axes) == 0
E       assert 1 == 0

```

Unfortunately, I observed multiple issues with gaussian algorithm(namely usage of `joblib.Parallel`). I here want to suggest we stop using it.
1. With gaussian algorithm, memory load gets really high both on ubuntu and osx(haven't tested on Windows). Worse than having high memory load, joblib is not freeing memory after end of its execution. If you accidentally run a test case back to back, operating systems fails and crashes other applications till it can breathe again.  

2. Sometimes (maybe safe to say often?) Loky processes do not join back properly after they are done on ubuntu(haven't tested on Windows). This is not related to GUI/QThread, I tested in a python terminal and vanilla script and observed the same issue. Maybe it is due to usage of `Parallel` and `delayed` together? I am not sure. I've checked their documentation to see if we can force processes to join with another call but couldn't find anything.

**Pull request closed without merging**
